matrimony website/matrimony/account/urls.py
from django.urls import path
from . import views
from .views import *
from .views import CustomPasswordChangeView


app_name = 'account'


urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('register/', views.register, name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('regprofile1/', Regpro1View.as_view(), name='regprofile1'),
    path('regprofile2/', views.regprofile2, name='regprofile2'),

    path('employee/', EmployeeView.as_view(), name='employee'),
    path('jobseeker/', JobseekerView.as_view(), name='jobseeker'),

    path('profile/edit/', ProfileUpdateView.as_view(), name='profile_edit'),
    path('profile/', ProfileView.as_view(), name='profile'),

    path('password_change/', CustomPasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', TemplateView.as_view(template_name='accounts/password_change_done.html'), name='password_change_done'),


     
    path('relations/', views.relations, name='relations'),


    path('delete-profile/', DeleteProfileView.as_view(), name='delete_profile'),



]

matrimony website/matrimony/matrimony/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('account.urls',namespace='account')),
    path('user/', include('user.urls',namespace='user',))

]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

matrimony website/matrimony/user/urls.py
from django.urls import path
from . import views


from .views import *
from .views import send_friend_request, accept_friend_request, reject_friend_request, view_friend_requests, friends_list
from .views import inbox_view, send_message_view,chat_view,partner_search_view



app_name = 'user'
urlpatterns = [
    path('',views.home,name='home'),
    path('about/',views.about,name='about'),
    path('matrimonyhome/',views.matrimonyhome,name='matrimonyhome'),
    path('personaldetails/', PersonalDetailsView.as_view(), name='personaldetails'),
    path('partnerpreferance/',PartnerpreferanceView.as_view(),name='partner_preference'),
    path('grid/', Grid.as_view(), name='grid'),
    path('partner/<int:pk>/', PartnerProfileView.as_view(), name='partner_profile'),  # Add this line

    path('send_request/<int:user_id>/', send_friend_request, name='send_friend_request'),
    path('accept_request/<int:request_id>/', accept_friend_request, name='accept_friend_request'),
    path('reject_request/<int:request_id>/', reject_friend_request, name='reject_friend_request'),
    path('friend_requests/', view_friend_requests, name='friend_requests'),
    path('friends/', friends_list, name='friends_list'),
    path('remove_friend/<int:friend_id>/', remove_friend, name='remove_friend'),



    # Add other URL patterns here
    path('inbox/', inbox_view, name='inbox'),
    path('send_message/<int:user_id>/', send_message_view, name='send_message'),
    path('chatbox/<int:user_id>/', chat_view, name='chatbox'),


    path('add_to_favorites/<int:profile_id>/', views.add_to_favorites, name='add_to_favorites'),
    path('remove_from_favorites/<int:profile_id>/', views.remove_from_favorites, name='remove_from_favorites'),

    path('favorites/', favorites_view, name='favorites'),


    path('subscription/', SubscriptionView.as_view(), name='subscription'),
    path('create-checkout-session/', CreateCheckoutSessionView.as_view(), name='create_checkout_session'),
    path('success/', SuccessView.as_view(), name='success'),
    path('failed/', FailedView.as_view(), name='failed'),
    path('webhook/', StripeWebhookView.as_view(), name='stripe_webhook'),


    path('search/', partner_search_view, name='partner_search'),
    
    path('profile-details/', profile_details_view, name='profile_details'),



]

matrimony website/matrimony/user/views.py
from django.shortcuts import render,redirect,get_object_or_404
from.forms import PersonalDetailForm,PartnerPreferanceForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from.models import PersonalDetails,PartnerPreferance,Subscription
from django.urls import reverse_lazy,reverse
from django.views.generic import View, TemplateView, DetailView, UpdateView, FormView
from account.models import User
from django.db.models import Q
from datetime import date
from .models import FriendRequest,Friend
from django.contrib.auth import get_user_model
from .models import Message, User,Favorite
from .forms import MessageForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import stripe
from django.conf import settings
from django.http import JsonResponse
import json
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.views import View
from .models import Subscription, User
import logging
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from account.models import User  

from urllib.parse import urlencode













User = get_user_model()

# Create your views here.
@login_required
def home(request):
    print("Home view called")
    personal_details = PersonalDetails.objects.filter(user=request.user).first()
    if personal_details:
        print("PersonalDetails found:", personal_details)
        is_personal_details_filled = personal_details.is_filled()
        print(f"Personal details filled: {is_personal_details_filled}")
    else:
        print("No PersonalDetails found for the user.")
        is_personal_details_filled = False
    return render(request, 'home.html', {'is_personal_details_filled': is_personal_details_filled})


def about(request):
    return render(request,'about.html')

def matrimonyhome(request):
    return render(request,'matrimonyhome.html')


class PersonalDetailsView(LoginRequiredMixin, UpdateView):
    model = PersonalDetails
    form_class = PersonalDetailForm
    template_name = 'personaldet.html'
    success_url = reverse_lazy('user:partner_preference')  # Ensure this URL exists in your URLconf

    def get_success_url(self):
        # Check if the partner preference form is filled
        partner_preference = PartnerPreferance.objects.filter(user=self.request.user).first()
        if partner_preference and partner_preference.is_filled() and self.object.is_filled():
            return reverse_lazy('user:partner_preference')
        return reverse_lazy('user:partner_preference')

    

    def get_object(self, queryset=None):
        # Ensure we get the PersonalDetails object for the logged-in user, creating one if it doesn't exist
        obj, created = PersonalDetails.objects.get_or_create(user=self.request.user)
        return obj

    def form_valid(self, form):
        form.instance.user = self.request.user
        print("Form data:", form.cleaned_data)  # Print the cleaned data
        response = super().form_valid(form)
        print("Form is valid, redirecting to:", self.get_success_url())
        return response
    
    def form_invalid(self, form):
        print("Form is invalid:", form.errors)
        return super().form_invalid(form)

    

class PartnerpreferanceView(LoginRequiredMixin, UpdateView):
    model = PartnerPreferance
    form_class = PartnerPreferanceForm
    template_name = 'partner.html'
    success_url = reverse_lazy('user:grid')  # Replace 'success_url' with your actual success URL name

    def get_success_url(self):
        # Check if the personal details form is filled
        personal_details = PersonalDetails.objects.filter(user=self.request.user).first()
        if personal_details and personal_details.is_filled() and self.object.is_filled():
            return reverse_lazy('user:grid')
        return reverse_lazy('user:grid')

    def get_object(self, queryset=None):
        obj, created = PartnerPreferance.objects.get_or_create(user=self.request.user)
        return obj

    def form_valid(self, form):
        # Ensure the user is set correctly
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    def form_invalid(self, form):
        print("Form is invalid:", form.errors)
        return super().form_invalid(form)
    


class Grid(LoginRequiredMixin, TemplateView):
    template_name = 'partners_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        try:
            partner_preference = user.partner_preference  # Use the correct related name
            profiles = User.objects.filter(
                age__gte=partner_preference.age_min,
                age__lte=partner_preference.age_max,
                personaldetails__caste=partner_preference.caste,
                personaldetails__religion=partner_preference.religion,
                personaldetails__height__gte=partner_preference.height_min,
                personaldetails__height__lte=partner_preference.height_max,
                personaldetails__weight__gte=partner_preference.weight_min,
                personaldetails__weight__lte=partner_preference.weight_max,
                personaldetails__income__gte=partner_preference.income_min,
                personaldetails__income__lte=partner_preference.income_max,
                gender=partner_preference.gender,
                 qualification=partner_preference.qualification
            ).exclude(id=user.id).select_related('personaldetails').prefetch_related('personaldetails')
            context['profiles'] = profiles
        except PartnerPreferance.DoesNotExist:
            context['profiles'] = User.objects.none()  # If no partner preference, show no profiles
            for profile in profiles:
                print(f"Profile ID: {profile.pk}, Username: {profile.username}")

        except PartnerPreferance.DoesNotExist:
            context['profiles'] = User.objects.none() 

        return context


class PartnerProfileView(DetailView):
    model = User
    template_name = 'partner_profile.html'
    context_object_name = 'partner'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        partner = self.object  # This is the User object for the partner

        # Check if the current user has an active subscription
        user_subscription = Subscription.objects.filter(user=self.request.user, active=True).exists()

        # Get partner preferences if available
        try:
            preference = PartnerPreferance.objects.get(user=partner)
        except PartnerPreferance.DoesNotExist:
            preference = None

        # Add subscription status and preference to the context
        context['has_subscription'] = user_subscription
        context['preference'] = preference
        
        return context
    


# @login_required
# def send_friend_request(request, user_id):
#     to_user = get_object_or_404(User, id=user_id)
    
#     # Check if they are already friends
#     if Friend.objects.filter(
#         (Q(current_user=request.user) & Q(users=to_user)) | 
#         (Q(current_user=to_user) & Q(users=request.user))
#     ).exists():
#         messages.info(request, "You are already friends with this user.")
#         return redirect(request.GET.get('next', 'user:grid'))
    
#     # Check if a friend request already exists
#     if FriendRequest.objects.filter(
#         from_user=request.user,
#         to_user=to_user
#     ).exists():
#         messages.info(request, "Friend request already sent.")
#     else:
#         FriendRequest.objects.create(from_user=request.user, to_user=to_user)
#         messages.success(request, "Friend request sent successfully.")
    
#     return redirect(request.GET.get('next', 'user:grid'))



@login_required
def accept_friend_request(request, request_id):
    friend_request = get_object_or_404(FriendRequest, id=request_id)
    if friend_request.to_user == request.user:
        friend_request.accepted = True
        friend_request.save()
        Friend.make_friend(request.user, friend_request.from_user)
        Friend.make_friend(friend_request.from_user, request.user)
    return redirect('user:friend_requests')

@login_required
def reject_friend_request(request, request_id):
    friend_request = get_object_or_404(FriendRequest, id=request_id)
    if friend_request.to_user == request.user:
        friend_request.delete()
    return redirect('user:friend_requests')

@login_required
def view_friend_requests(request):
    incoming_requests = FriendRequest.objects.filter(to_user=request.user, accepted=False)
    outgoing_requests = FriendRequest.objects.filter(from_user=request.user, accepted=False)
    return render(request, 'friend_requests.html', {'incoming_requests': incoming_requests, 'outgoing_requests': outgoing_requests})

@login_required
def friends_list(request):
    try:
        friend = Friend.objects.get(current_user=request.user)
        friends = friend.users.all()
    except Friend.DoesNotExist:
        friends = []

    return render(request, 'friends_list.html', {'friends': friends})



@login_required
def remove_friend(request, friend_id):
    try:
        friend = get_object_or_404(User, id=friend_id)
        friend_list = get_object_or_404(Friend, current_user=request.user)
        if friend in friend_list.users.all():
            friend_list.users.remove(friend)
            # Optionally, you might want to remove the user from the friend’s list too
            friend_list_of_friend = get_object_or_404(Friend, current_user=friend)
            if request.user in friend_list_of_friend.users.all():
                friend_list_of_friend.users.remove(request.user)
    except Friend.DoesNotExist:
        pass  # Handle the case where the user is not in any friend list

matrimony website/matrimony/user/templates/usernav/shared/home.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    
    {% block meta %}
        
    {% endblock meta %}
        
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">


    <!-- Bootstrap CSS v5.2.1 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />

    {% block styles %}
        
    {% endblock styles %}
        
</head>

<body>
    <header>
        {% include 'shared/navbar.html' %}
    </header>
    <main>
        
        {% block content %}
            
        {% endblock content %}
            
    </main>
    <footer>
        <!-- place footer here -->
    </footer>
    <!-- Bootstrap JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
    
    {% block scripts %}
        
    {% endblock scripts %}
        
</body>

</html>

matrimony website/matrimony/user/templates/usernav/shared/navbar.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    
    {% block meta %}
        
    {% endblock meta %}
        
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Bootstrap CSS v5.2.1 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

    {% block styles %}
        
    {% endblock styles %}
    <style>
        .prosubnav:hover {
            background-color: rgb(232, 220, 220);
             
        }
        .mnav:hover{
            /* background-color: rgb(69, 73, 72); */
            background-color: rgb(176, 176, 176);

        }
        </style>
        
</head>

<body>
    <header>
      
            
            
            
                    
            
            <nav class="navbar navbar-expand-sm navbar-dark " style="background-color: rgb(90, 26, 53);">
                <div class="container">
            
                    <a class="navbar-brand" href="#">Matrimony         
                        <img src="{% static 'images/logo.png' %}" alt="" width="60" height="60">
                    </a>
            
                
                    <div class="collapse navbar-collapse" id="collapsibleNavId">
                        <ul class="navbar-nav me-auto mt-2 mt-lg-0">
                            <li class="nav-item mnav">
                                <a class="nav-link" href="{% url 'user:matrimonyhome' %}">Home</a>
                            </li>
                            <li class="nav-item mnav">
                                <a class="nav-link" href="{% url 'user:about' %}">About</a>
                            </li>
                            <li class="nav-item mnav">
                                <a class="nav-link" href="#">Contact</a>
                            </li>
                          
                       
                        {% if not user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account:login' %}">Login</a>
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link" href="{% url 'account:register' %}">Register</a>
                            </li>
                        {% endif %}
                      
               
                        </ul>
                 
                              
                        {% if user.is_authenticated %}

       
                       
                        
                        <ul class="navbar-nav ms-auto mt-2 mt-lg-0 me-2" >
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <img src="{{user.profile_photo.url }}" alt="Profile Photo" width="50" height="50" style="border-radius: 25px;border: 2px solid rgb(90, 89, 86);" class="">
                                </a>
                                <ul class="dropdown-menu" style="background-color:rgb(90, 26, 53);">
                                  <li class="dropdown-item mnav">
                                    <a style="color: rgb(243, 244, 241);text-decoration: none;" href="{% url 'account:profile' %}">Profile</a>
                                   </li>
                                  <li class="dropdown-item mnav">
                                    <a href="{% url 'user:inbox' %}" style="text-decoration: none;color:white;">Chats</a>
                                  </li>
                                  <li class="dropdown-item mnav">
                                    <a href="{% url 'user:grid' %}" style="text-decoration: none;color:white;">Partner page</a>
                                  </li>
                                  <li class="dropdown-item mnav">
                                    <a href="{% url 'user:subscription' %}" style="text-decoration: none;color:white;">Plans</a>
                                  </li>
                                  <li class="dropdown-item mnav">
                                    <a href="{% url 'user:profile_details' %}" style="text-decoration: none;color:white;">more info</a>
                                  </li>
                                  <li><hr class="dropdown-divider"></li>
                                  <li><a class="dropdown-item mnav " style="color: white;" href="{% url 'account:logout' %}">Logout</a></li>
                                </ul>
                              </li>
                        </ul>
                        {% endif %}
                    
                        
                        <form class="d-flex my-2 my-lg-0" method="get" action="{% url 'user:partner_search' %}">
                            <input class="form-control me-sm-2" type="text" name="name" placeholder="Search by name" />
                            <button class="btn my-2 my-sm-0" style="color: rgb(246, 245, 245); background-color: rgb(230, 156, 156); border-color: rgb(230, 156, 156);" type="submit">
                                Search
                            </button>
                        </form>
                        
                        {% if user.is_authenticated %}
                        <li class="nav-item mt-2 fs-4 mx-3  " style="list-style: none;">
                            <a href="{% url 'user:favorites' %}">
                                <i class="bi bi-heart text-danger" ></i>
                            </a>

                        </li>
                        {% endif %}
                       
                    </div>
                </div>
            </nav>
    </header>
    <main>

        
        {% block content %}
            
        {% endblock content %}
            
    </main>
    <footer>
        <!-- place footer here -->
    </footer>
    <!-- Bootstrap JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
    
    {% block scripts %}
        
    {% endblock scripts %}
        
</body>

</html>